### ISSUE TITLE
lvtk recipe install failed

### ISSUE THREAD

**Issue by Rezzonics** [auto3000/pedalpi-dev-platform#13]
I think there is an issue with lvtk recipe. Install is looking for the files in the wrong folder:
ERROR: lvtk-1.0.2-r0 do_install: Execution of '/home/amlogic-bsp/build/tmp/work/aarch64-poky-linux/lvtk/1.0.2-r0/temp/run.do_install.9193' failed with exit code 1:
Waf: Entering directory `/home/amlogic-bsp/build/tmp/work/aarch64-poky-linux/lvtk/1.0.2-r0/build'
could not find 'build/version.h' in /home/amlogic-bsp/build/tmp/work/aarch64-poky-linux/lvtk/1.0.2-r0/git
WARNING: /home/amlogic-bsp/build/tmp/work/aarch64-poky-linux/lvtk/1.0.2-r0/temp/run.do_install.9193:1 exit 1 from 'waf_do_install'

ERROR: Logfile of failure stored in: /home/amlogic-bsp/build/tmp/work/aarch64-poky-linux/lvtk/1.0.2-r0/temp/log.do_install.9193

**Comment by auto3000** [comment]
lvtk is using waf (=makefile) for build, this is pretty robust. Maybe this
version of lvtk is not compatible with the python/waf installation on zeus.
You can try to update to latest lvtk, maybe the author did use a newer waf
script that could be compatible. Let me know if you this is successful or
not.

**Comment by auto3000** [comment]
This problem is occurring on "zeus" poky release. This problem is fixed by https://github.com/auto3000/meta-pedalpi/commit/d6a9d38d41facac1a65d7c3c62fcf90bd0afcf84

Resolved.
